/// <reference lib="webworker" />
import { clientsClaim } from 'workbox-core'
import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching'
import { NavigationRoute, registerRoute } from 'workbox-routing'

declare let self: ServiceWorkerGlobalScope

// Take control of all pages as soon as the SW is activated
self.skipWaiting()
clientsClaim()

// Clean up old caches
cleanupOutdatedCaches()

// Precache all of the assets generated by your build process
// This is the critical line that must be present
precacheAndRoute(self.__WB_MANIFEST)

// Handle navigation requests (for SPA routing)
const navRoute = new NavigationRoute(async ({ request }) => {
  try {
    return await fetch(request)
  } catch {
    const cachedResponse = await caches.match('/')
    if (cachedResponse) {
      return cachedResponse
    }
    return await fetch('/')
  }
})

registerRoute(navRoute)

// Listen for messages from the app
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting()
  }
})
